# Generated by Django 4.0.3 on 2022-03-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(max_length=10)),
                ('userFirstName', models.TextField(max_length=10)),
                ('userLastName', models.TextField(max_length=10)),
                ('userProgress', models.IntegerField(max_length=3)),
                ('userResult', models.TextField(default='Not Taken The Test Yet')),
            ],
        ),
    ]
