# Generated by Django 4.0.3 on 2022-03-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_user_id_remove_user_userprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
