# Generated by Django 4.0.3 on 2022-03-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='result',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
