# Generated by Django 4.0.4 on 2022-05-06 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0006_rename_result_questions_mathematical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Mathematical',
            field=models.CharField(default='white', max_length=70),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Programming',
            field=models.CharField(default='white', max_length=70),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Theory',
            field=models.CharField(default='white', max_length=70),
        ),
        migrations.AlterField(
            model_name='questions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
