# Generated by Django 4.0.3 on 2022-03-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('address', models.TextField(default='/404')),
                ('instructor', models.CharField(default='Unknown instructor', max_length=25)),
                ('numberofVedioes', models.IntegerField()),
            ],
        ),
    ]
