# Generated by Django 4.0.3 on 2022-03-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
